repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.19.1
    hooks:
    - id: latexindent

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-gfm
