name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build with latex-action
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}

      - name: Move document
        run: mkdir -p artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./artifacts/

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./artifacts

  archive:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Format date and time for filename
        id: datetime
        run: echo "DATETIME=$(date +'%d%m%y_%H%M')" >> $GITHUB_ENV

      - name: Rename PDF with date and time
        run: mv artifacts/*/*.pdf artifacts/resume_${{ env.DATETIME }}.pdf

      - name: Allow archive folder in git
        run: |
          echo "!archive/" >> .gitignore
          echo "!archive/*.pdf" >> .gitignore

      - name: Commit and push to archive branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout archive || git checkout --orphan archive
          mkdir -p archive
          mv artifacts/*.pdf archive/
          git add -f archive/*.pdf
          git commit -m "Add resume_${{ env.DATETIME }}.pdf"
          git push origin archive --force
