name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build with latex-action
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: Move document
        run: mkdir -p artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./artifacts/
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: move
        run: mkdir -p deploy && mv artifacts/*/* deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
