name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build with latex-action
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}

      - name: Move document
        run: mkdir -p artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./artifacts/

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifact for deployment
        run: mkdir -p deploy && mv artifacts/*/*.pdf deploy/latest.pdf

      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: deploy
          force_orphan: true
          enable_jekyll: true
